version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - docker/check
      - aws-cli/setup
      - run:
          name: Build and push Docker images
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose -f docker-compose-build.yaml build --parallel
            docker push skandaprasad98/reverseproxy:latest
            docker push skandaprasad98/udagram-api-user:latest
            docker push skandaprasad98/udagram-api-feed:latest
            docker push skandaprasad98/udagram-frontend:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          context: dockerhub-credentials