apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-user
  labels:
    app: udagram-backend-user
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: udagram-backend-user